# Generated by Django 2.2.7 on 2019-12-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=100)),
                ("body", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        )
    ]
