# Generated by Django 2.2.1 on 2019-12-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("feedback", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="comment", name="email", field=models.EmailField(max_length=100)
        )
    ]
