# Generated by Django 2.2.1 on 2019-12-04 12:22

from django.db import migrations


def update_extraction_script(apps, schema_editor):
    Text = apps.get_model("dashboard", "ExtractedText")
    Script = apps.get_model("dashboard", "Script")
    script = Script.objects.filter(pk=14).first()
    if script:
        docs = Text.objects.filter(pk__in=[1372609, 1372610])
        docs.update(extraction_script=script)


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0139_audit_log_indexes'),
    ]

    operations = [
        migrations.RunPython(
            update_extraction_script, reverse_code=migrations.RunPython.noop
        ),
    ]
