# Generated by Django 2.2.6 on 2019-12-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0140_update_documents")]

    operations = [
        migrations.AddField(
            model_name="rawchem",
            name="component",
            field=models.CharField(
                blank=True,
                help_text="product component",
                max_length=200,
                null=True,
                verbose_name="Component",
            ),
        ),
        # Generate the new lookup table by selecting unique combinations of
        # sid, true_cas, and true_chemname from dashboard_dsstoxsubstance
        migrations.RunSQL(
            """
            UPDATE dashboard_rawchem rc 
            inner join dashboard_extractedchemical ec on 
                ec.rawchem_ptr_id = rc.id
            SET rc.component = ec.component
        """,
            reverse_sql=migrations.RunPython.noop,
        ),
        migrations.RemoveField(model_name="extractedchemical", name="component"),
    ]
