# Generated by Django 2.2.9 on 2020-01-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0142_audit_log_triggers")]

    operations = [
        migrations.AlterField(
            model_name="datagroup",
            name="zip_file",
            field=models.CharField(max_length=300),
        )
    ]
