# Generated by Django 2.2.9 on 2020-01-31 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0143_zip_file_field")]

    operations = [
        migrations.CreateModel(
            name="ExtractedHabitsAndPracticesDataType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("title", models.CharField(max_length=50)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.AddField(
            model_name="extractedhabitsandpractices",
            name="data_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="dashboard.ExtractedHabitsAndPracticesDataType",
            ),
        ),
    ]
