# Generated by Django 2.2.4 on 2020-01-27 06:42

from itertools import chain

from django.db import migrations, models
import django.db.models.deletion

from dashboard.models import AuditLog


def transfer_funcuses(apps, schema_editor):

    XChemical = apps.get_model("dashboard", "ExtractedChemical")
    XFunctionalUse = apps.get_model("dashboard", "ExtractedFunctionalUse")
    XListPresence = apps.get_model("dashboard", "ExtractedListPresence")
    FunctionalUse = apps.get_model("dashboard", "FunctionalUse")
    chems = list(
        chain(
            XChemical.objects.all(),
            XFunctionalUse.objects.all(),
            XListPresence.objects.all(),
        )
    )
    for chem in chems:
        if chem.report_funcuse:
            FunctionalUse.objects.create(
                report_funcuse=chem.report_funcuse, chem_id=chem.rawchem_ptr_id
            )


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0145_move_datadoc_files")]

    operations = [
        migrations.CreateModel(
            name="FunctionalUse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "report_funcuse",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Reported functional use",
                    ),
                ),
                (
                    "clean_funcuse",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Cleaned functional use",
                    ),
                ),
                (
                    "chem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="functional_uses",
                        to="dashboard.RawChem",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.RunPython(transfer_funcuses, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(model_name="extractedchemical", name="report_funcuse"),
        migrations.RemoveField(
            model_name="extractedfunctionaluse", name="report_funcuse"
        ),
        migrations.RemoveField(
            model_name="extractedlistpresence", name="report_funcuse"
        ),
    ]
