# Generated by Django 2.2.9 on 2020-02-24 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0147_producttopuc_bulk_updates")]

    operations = [
        migrations.CreateModel(
            name="ExtractedLMDoc",
            fields=[
                (
                    "extractedtext_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dashboard.ExtractedText",
                    ),
                ),
                (
                    "study_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Targeted", "Targeted"),
                            ("Non-Targeted", "Non-Targeted"),
                            ("Other", "Other"),
                        ],
                        max_length=12,
                        verbose_name="Study Type",
                    ),
                ),
                (
                    "pmid",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9]*$", "PMID must be numerical"
                            )
                        ],
                        verbose_name="PMID",
                    ),
                ),
                (
                    "media",
                    models.CharField(blank=True, max_length=100, verbose_name="Media"),
                ),
            ],
            options={"abstract": False},
            bases=("dashboard.extractedtext",),
        )
    ]
