# Generated by Django 2.2.10 on 2020-03-03 10:57

from django.db import migrations, models
import django.db.models.deletion


def drop_existing_extracted_hnp(apps, schema_editor):
    ExtractedHabitsAndPractices = apps.get_model(
        "dashboard", "ExtractedHabitsAndPractices"
    )
    db_alias = schema_editor.connection.alias
    ExtractedHabitsAndPractices.objects.using(db_alias).delete()


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0148_extractedlmdoc")]

    operations = [
        migrations.RunPython(drop_existing_extracted_hnp, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="extractedhabitsandpractices", name="duration"
        ),
        migrations.RemoveField(
            model_name="extractedhabitsandpractices", name="duration_unit"
        ),
        migrations.RemoveField(
            model_name="extractedhabitsandpractices", name="frequency"
        ),
        migrations.RemoveField(
            model_name="extractedhabitsandpractices", name="frequency_unit"
        ),
        migrations.RemoveField(model_name="extractedhabitsandpractices", name="mass"),
        migrations.RemoveField(
            model_name="extractedhabitsandpractices", name="mass_unit"
        ),
        migrations.RemoveField(
            model_name="extractedhabitsandpractices", name="prevalence"
        ),
        migrations.AlterField(
            model_name="extractedhabitsandpractices",
            name="data_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="dashboard.ExtractedHabitsAndPracticesDataType",
            ),
        ),
    ]
