# Generated by Django 2.2.10 on 2020-03-12 11:56

from django.db import migrations
from django.db.models import Q


def clear_unknown_product_fields(apps, schema_editor):
    ProductModel = apps.get_model("dashboard", "Product")
    for product in ProductModel.objects.filter(
        Q(brand_name="unknown") | Q(manufacturer="unknown")
    ).all():
        if product.brand_name == "unknown":
            product.brand_name = ""
        if product.manufacturer == "unknown":
            product.manufacturer = ""
        product.save()


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0151_unknown_product_title")]

    operations = [
        migrations.RunPython(
            clear_unknown_product_fields, reverse_code=migrations.RunPython.noop
        )
    ]
