# Generated by Django 2.2.10 on 2020-03-03 16:28

import dashboard.models.product
from dashboard.utils import uuid_file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0152_product_data_cleanup_brand_and_manufacturer")]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="The product's image file",
                null=True,
                upload_to=uuid_file,
                validators=[dashboard.models.product.validate_product_image_size],
            ),
        )
    ]
