# Generated by Django 2.2.11 on 2020-03-26 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0153_product_add_image_field")]

    operations = [
        migrations.CreateModel(
            name="DuplicateProduct",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dashboard.Product",
                    ),
                ),
                (
                    "source_upc",
                    models.CharField(
                        db_index=True, help_text="Source UPC", max_length=60
                    ),
                ),
            ],
            options={"abstract": False},
            bases=("dashboard.product",),
        )
    ]
