# Generated by Django 2.2.11 on 2020-03-31 16:26

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0154_duplicateproduct")]

    operations = [
        migrations.CreateModel(
            name="ExtractedHabitsAndPracticesTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "definition",
                    models.CharField(
                        blank=True, max_length=750, null=True, verbose_name="Definition"
                    ),
                ),
            ],
            options={
                "verbose_name": "Extracted habits and practices keyword",
                "verbose_name_plural": "Extracted habits and practices keywords",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ExtractedHabitsAndPracticesTagKind",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Extracted habits and practices keyword kind",
                "verbose_name_plural": "Extracted habits and practices keyword kinds",
            },
        ),
        migrations.CreateModel(
            name="ExtractedHabitsAndPracticesToTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.ExtractedHabitsAndPractices",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_extractedhabitsandpracticestotag_items",
                        to="dashboard.ExtractedHabitsAndPracticesTag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Extracted habits and practices to keyword",
                "verbose_name_plural": "Extracted habits and practices to keywords",
                "ordering": ("content_object",),
            },
        ),
        migrations.AddField(
            model_name="extractedhabitsandpracticestag",
            name="kind",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="dashboard.ExtractedHabitsAndPracticesTagKind",
            ),
        ),
        migrations.AddField(
            model_name="extractedhabitsandpractices",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="dashboard.ExtractedHabitsAndPracticesToTag",
                to="dashboard.ExtractedHabitsAndPracticesTag",
                verbose_name="Tags",
            ),
        ),
    ]
