# Generated by Django 2.2.10 on 2020-03-27 12:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0155_habits_and_practices_tags")]

    operations = [
        migrations.AlterField(
            model_name="datadocument",
            name="note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Long-form notes about the document",
                verbose_name="note",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="datadocument",
            name="raw_category",
            field=models.CharField(
                blank=True,
                default="",
                help_text="the category applied by the document's originating dataset",
                max_length=1000,
                verbose_name="raw category",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="datadocument",
            name="subtitle",
            field=models.CharField(
                blank=True,
                default="",
                help_text="the subtitle of the document",
                max_length=250,
                verbose_name="subtitle",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="datadocument",
            name="url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="an optional URL to the document's remote source",
                max_length=375,
                validators=[django.core.validators.URLValidator()],
                verbose_name="URL",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="datagroup",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="datasource",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="documenttype",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dsstoxlookup",
            name="true_cas",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="True CAS"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dsstoxlookup",
            name="true_chemname",
            field=models.CharField(
                blank=True,
                default="",
                max_length=500,
                verbose_name="True chemical name",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="extractedchemical",
            name="raw_central_comp",
            field=models.CharField(
                blank=True,
                default="",
                help_text="central composition",
                max_length=100,
                verbose_name="Central",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="extractedchemical",
            name="raw_max_comp",
            field=models.CharField(
                blank=True,
                default="",
                help_text="maximum composition",
                max_length=100,
                verbose_name="Maximum",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="extractedchemical",
            name="raw_min_comp",
            field=models.CharField(
                blank=True,
                default="",
                help_text="minimum composition",
                max_length=100,
                verbose_name="Minimum",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="extractedcpcat",
            name="cat_code",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Cat code"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="extractedcpcat",
            name="cpcat_code",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="ACToR snaid"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="extractedcpcat",
            name="cpcat_sourcetype",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="CPCat source"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="extractedcpcat",
            name="description_cpcat",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="CPCat cassette"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="extractedhabitsandpracticesdatatype",
            name="description",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="extractedhhdoc",
            name="facility",
            field=models.CharField(
                blank=True, default="", max_length=75, verbose_name="Facility"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="extractedhhdoc",
            name="naics_code",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="NAICS Code"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="extractedhhdoc",
            name="occupation",
            field=models.CharField(
                blank=True, default="", max_length=75, verbose_name="Occupation"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="extractedhhdoc",
            name="population_age",
            field=models.CharField(
                blank=True, default="", max_length=75, verbose_name="Age of Population"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="extractedhhdoc",
            name="population_gender",
            field=models.CharField(
                blank=True,
                choices=[("BO", "Both"), ("FM", "Female"), ("MA", "Male")],
                default="",
                max_length=2,
                verbose_name="Gender of Population",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="extractedhhdoc",
            name="population_other",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Other Description of Population",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="extractedhhdoc",
            name="sampling_date",
            field=models.CharField(
                blank=True, default="", max_length=75, verbose_name="Date of Sampling"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="extractedhhdoc",
            name="study_location",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Study Location"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="extractedhhrec",
            name="analytical_method",
            field=models.TextField(
                blank=True, default="", verbose_name="Analytical Method"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="extractedhhrec",
            name="media",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="Media"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="extractedhhrec",
            name="num_measure",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Numeric Measure"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="extractedhhrec",
            name="num_nondetect",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Numeric Nondetect"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="extractedhhrec",
            name="sampling_method",
            field=models.TextField(
                blank=True, default="", verbose_name="Sampling Method"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="extractedlistpresencetag",
            name="definition",
            field=models.CharField(
                blank=True, default="", max_length=750, verbose_name="Definition"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="extractedtext",
            name="doc_date",
            field=models.CharField(
                blank=True, default="", max_length=25, verbose_name="Document date"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="extractedtext",
            name="prod_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The name of the product according to the extracted document",
                max_length=500,
                verbose_name="Product name",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="extractedtext",
            name="rev_num",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Revision number"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="functionalusecategory",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="grouptype",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="brand_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="brand name",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="color",
            field=models.CharField(
                blank=True, default="", help_text="color", max_length=100
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="large_image",
            field=models.CharField(
                blank=True, default="", help_text="large image", max_length=500
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="long_description",
            field=models.TextField(
                blank=True, default="", help_text="long description"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="manufacturer",
            field=models.CharField(
                blank=True, db_index=True, default="", help_text="title", max_length=250
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="medium_image",
            field=models.CharField(
                blank=True, default="", help_text="medium image", max_length=500
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="model_number",
            field=models.CharField(
                blank=True, default="", help_text="model number", max_length=200
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="short_description",
            field=models.TextField(
                blank=True, default="", help_text="short description"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.CharField(
                blank=True, default="", help_text="size", max_length=100
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="thumb_image",
            field=models.CharField(
                blank=True, default="", help_text="thumbnail image", max_length=500
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="url",
            field=models.CharField(
                blank=True, default="", help_text="URL", max_length=500
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="puctag",
            name="definition",
            field=models.TextField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="qanotes",
            name="qa_notes",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rawchem",
            name="component",
            field=models.CharField(
                blank=True,
                default="",
                help_text="product component",
                max_length=200,
                verbose_name="Component",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rawchem",
            name="raw_cas",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Raw CAS",
                max_length=100,
                verbose_name="Raw CAS",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rawchem",
            name="raw_chem_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Raw chemical name",
                max_length=1300,
                verbose_name="Raw chemical name",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rawchem",
            name="rid",
            field=models.CharField(
                blank=True, default="", help_text="RID", max_length=50
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rawchem",
            name="temp_obj_name",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="script",
            name="url",
            field=models.CharField(
                blank=True,
                default="",
                max_length=225,
                validators=[django.core.validators.URLValidator()],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sourcecategory",
            name="path",
            field=models.CharField(
                blank=True, default="", help_text="path", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sourcecategory",
            name="source_id",
            field=models.CharField(
                blank=True, default="", help_text="source ID", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sourcecategory",
            name="source_parent_id",
            field=models.CharField(
                blank=True, default="", help_text="source parent ID", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="taxonomy",
            name="category_code",
            field=models.CharField(blank=True, default="", max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="taxonomy",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="taxonomysource",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="unittype",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Unit Type"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="weightfractiontype",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="extractedhabitsandpracticestag",
            name="definition",
            field=models.CharField(
                blank=True, default="", max_length=750, verbose_name="Definition"
            ),
            preserve_default=False,
        ),
    ]
