# Generated by Django 2.2.10 on 2020-04-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0156_remove_nulls")]

    operations = [
        migrations.AlterModelOptions(
            name="extractedhabitsandpracticestag",
            options={
                "ordering": ("kind", "name"),
                "verbose_name": "Extracted habits and practices keyword",
                "verbose_name_plural": "Extracted habits and practices keywords",
            },
        )
    ]
