# Generated by Django 2.2.10 on 2020-04-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0158_add_unique_constraints")]

    operations = [
        migrations.AlterField(
            model_name="extractedhabitsandpractices",
            name="PUCs",
            field=models.ManyToManyField(
                blank=True,
                through="dashboard.ExtractedHabitsAndPracticesToPUC",
                to="dashboard.PUC",
            ),
        )
    ]
