# Generated by Django 2.2.11 on 2020-04-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0159_hp_pucs_blank_attribute")]

    operations = [
        migrations.AddField(
            model_name="datadocument",
            name="epa_reg_number",
            field=models.CharField(
                blank=True,
                help_text="the document's EPA registration number",
                max_length=25,
                verbose_name="EPA reg. no.",
            ),
        )
    ]
