# Generated by Django 2.2.11 on 2020-05-07 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0163_puc_kind_choices")]

    operations = [
        migrations.AddField(
            model_name="functionaluse",
            name="extraction_script",
            field=models.ForeignKey(
                limit_choices_to={"script_type": "FU"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.Script",
            ),
        ),
        migrations.AlterField(
            model_name="script",
            name="script_type",
            field=models.CharField(
                choices=[
                    ("DL", "download"),
                    ("EX", "extraction"),
                    ("PC", "product categorization"),
                    ("DC", "data cleaning"),
                    ("FU", "functional use cleaning"),
                ],
                default="EX",
                max_length=2,
            ),
        ),
    ]
