# Generated by Django 2.2.11 on 2020-06-18 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0165_extractedhp_options_and_extractedhpdoc")]

    operations = [
        migrations.AlterField(
            model_name="functionaluse",
            name="extraction_script",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"script_type": "FU"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.Script",
            ),
        )
    ]
