# Generated by Django 2.2.14 on 2020-09-08 12:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0168_detected_chem_flag"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ExtractedChemical", new_name="ExtractedComposition"
        )
    ]
