# Generated by Django 2.2.11 on 2020-11-10 08:31

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0171_product_uber_puc_view")]

    operations = [
        migrations.CreateModel(
            name="ProductUberPuc",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                )
            ],
            options={"db_table": "product_uber_puc", "managed": False},
        ),
        migrations.AlterModelOptions(
            name="extractedcomposition",
            options={
                "ordering": (
                    django.db.models.expressions.OrderBy(
                        django.db.models.expressions.F("component"), nulls_last=True
                    ),
                    django.db.models.expressions.OrderBy(
                        django.db.models.expressions.F("ingredient_rank"),
                        nulls_last=True,
                    ),
                )
            },
        ),
    ]
