# Generated by Django 2.2.14 on 2020-12-04 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def populate_methods(apps, schema_editor):
    ProductToPucClassificationMethod = apps.get_model(
        "dashboard", "ProductToPucClassificationMethod"
    )
    method_choices = {
        "MA": ["Manual", 1],
        "AU": ["Automatic", 2],
        "RU": ["Rule Based", 3],
        "MB": ["Manual Batch", 4],
        "BA": ["Bulk Assignment", 5],
    }
    for methodcode, methoddetails in method_choices.items():
        ProductToPucClassificationMethod.objects.create(
            code=methodcode, name=methoddetails[0], rank=methoddetails[1]
        )


def empty_reverse_function(apps, schema_editor):
    # The reverse function is not required
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0174_auditlog_extracted_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductToPucClassificationMethod",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "code",
                    models.CharField(
                        db_column="classification_method",
                        max_length=3,
                        primary_key=True,
                        serialize=False,
                        verbose_name="classification method code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="classification method name",
                    ),
                ),
                (
                    "rank",
                    models.PositiveSmallIntegerField(
                        unique=True, verbose_name="classification method rank"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PUC classification method",
                "verbose_name_plural": "PUC classification methods",
                "ordering": ["rank"],
            },
        ),
        migrations.RunPython(populate_methods, empty_reverse_function),
        migrations.AlterField(
            model_name="producttopuc",
            name="classification_method",
            
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="dashboard.ProductToPucClassificationMethod",
                db_column="classification_method",
            ),
        ),
    ]
