# Generated by Django 2.2.14 on 2020-12-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0174_auditlog_extracted_text")]

    operations = [
        migrations.AddField(
            model_name="datagroup",
            name="qa_summary_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="script",
            name="qa_summary_note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
