# Generated by Django 2.2.17 on 2020-12-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0180_productperpucviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='CumulativeProductsPerPuc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_count', models.IntegerField()),
                ('cumulative_product_count', models.IntegerField()),
                ('puc_level', models.IntegerField()),
            ],
            options={
                'db_table': 'cumulative_products_per_puc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductsPerPuc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_count', models.IntegerField()),
            ],
            options={
                'db_table': 'products_per_puc',
                'managed': False,
            },
        ),
    ]
