# Generated by Django 2.2.17 on 2020-12-30 12:30

from django.db import migrations
import django_db_views.migration_functions
import django_db_views.operations


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0181_productperpucmodels")]

    operations = [
        django_db_views.operations.ViewRunPython(
            code=django_db_views.migration_functions.ForwardViewMigration(
                "SELECT \n            product_uber_puc.puc_id AS puc_id,\n            dashboard_dsstoxlookup.sid as dsstoxlookup_id ,\n            count(product_uber_puc.product_id) AS product_count\n        FROM\n            product_uber_puc\n            INNER JOIN\n            dashboard_productdocument ON (product_uber_puc.product_id = dashboard_productdocument.product_id)\n                INNER JOIN\n            dashboard_datadocument ON (dashboard_productdocument.document_id = dashboard_datadocument.id)\n                INNER JOIN\n            dashboard_rawchem ON (dashboard_datadocument.id = dashboard_rawchem.extracted_text_id)\n                INNER JOIN\n            dashboard_dsstoxlookup ON (dashboard_rawchem.dsstox_id = dashboard_dsstoxlookup.id)\n            GROUP BY product_uber_puc.puc_id, sid\n            ",
                "products_per_puc_and_sid",
            ),
            reverse_code=django_db_views.migration_functions.BackwardViewMigration(
                "", "products_per_puc_and_sid"
            ),
            atomic=False,
        )
    ]
