# Generated by Django 2.2.17 on 2020-12-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0182_puc_sid_count_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsPerPucAndSid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_count', models.IntegerField()),
            ],
            options={
                'db_table': 'products_per_puc_and_sid',
                'managed': False,
            },
        ),
    ]
