# Generated by Django 2.2.18 on 2021-02-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0183_productsperuberpucviews")]

    operations = [
        migrations.AddField(
            model_name="extractedfunctionaluse",
            name="qa_flag",
            field=models.BooleanField(default=False),
        )
    ]
