# Generated by Django 2.2.17 on 2020-12-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0183_cumulative_counts_per_sid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CumulativeProductsPerPucAndSid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_count', models.IntegerField()),
                ('cumulative_product_count', models.IntegerField()),
                ('puc_level', models.IntegerField()),
            ],
            options={
                'db_table': 'cumulative_products_per_puc_and_sid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductsPerPucAndSid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_count', models.IntegerField()),
            ],
            options={
                'db_table': 'products_per_puc_and_sid',
                'managed': False,
            },
        ),
    ]
