# Generated by Django 2.2.17 on 2021-03-16 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("dashboard", "0185_remove_functionaluse_clean_funcuse")]

    operations = [
        migrations.AlterField(
            model_name="datadocument",
            name="data_group",
            field=models.ForeignKey(
                help_text="the DataGroup object to which the document belongs. The type of the data group determines "
                "which document types the document might be among, and determines much of the available "
                "relationships and behavior associated with the document's extracted data",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="datadocument_set",
                to="dashboard.DataGroup",
                verbose_name="data group",
            ),
        )
    ]
