# Generated by Django 2.2.17 on 2021-03-30 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0185_remove_functionaluse_clean_funcuse")]

    operations = [
        migrations.DeleteModel(name="CumulativeProductsPerPucAndSid"),
        migrations.DeleteModel(name="ProductsPerPuc"),
    ]
