# Generated by Django 2.2.17 on 2021-03-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0186_remove_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsPerPuc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_count', models.IntegerField()),
            ],
            options={
                'db_table': 'products_per_puc',
                'managed': False,
            },
        ),
    ]
