# Generated by Django 2.2.19 on 2021-04-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0188-functional-use-auditlog")]

    operations = [
        migrations.AddField(
            model_name="extractedhpdoc",
            name="extraction_completed",
            field=models.BooleanField(default=False),
        )
    ]
