# Generated by Django 2.2.19 on 2021-05-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("dashboard", "0189_extractedhpdoc_extraction_completed")]

    operations = [
        migrations.AddField(
            model_name="rawchem",
            name="provisional",
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(
            sql="""
            create index dashboard_rawchem_20char_rawchemname_index
            on dashboard_rawchem (raw_chem_name(20));""",
            reverse_sql="""
            drop index dashboard_rawchem_20char_rawchemname_index
            on dashboard_rawchem;""",
        ),
        migrations.RunSQL(
            sql="""
            create index dashboard_rawchem_20char_rawcas_index
            on dashboard_rawchem (raw_cas(20));""",
            reverse_sql="""
            drop index dashboard_rawchem_20char_rawcas_index
            on dashboard_rawchem;""",
        ),
    ]
