# Generated by Django 2.2.20 on 2021-06-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0192_extractedcomposition_has_composition_data")]

    operations = [
        migrations.AddField(
            model_name="producttopucclassificationmethod",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="puckind", name="description", field=models.TextField(blank=True)
        ),
    ]
