# Generated by Django 2.2.20 on 2021-06-08 16:34

import dashboard.models.data_source
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0193_puckind_cm_description")]

    operations = [
        migrations.AlterField(
            model_name="curationstep",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="curationstep",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="curationstep",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="curationstep",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="datadocument",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="datadocument",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="datadocument",
            name="pmid",
            field=models.CharField(
                blank=True,
                help_text="The PubMed ID, if the source document is an article in the PubMed library.",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]*$", "PMID must be numerical"
                    )
                ],
                verbose_name="PMID",
            ),
        ),
        migrations.AlterField(
            model_name="datadocument",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="datadocument",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="datagroup",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="datagroup",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="datagroup",
            name="data_source",
            field=models.ForeignKey(
                help_text="The data source to which the data group belongs.",
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.DataSource",
            ),
        ),
        migrations.AlterField(
            model_name="datagroup",
            name="description",
            field=models.TextField(
                blank=True, help_text="Long description of the data group."
            ),
        ),
        migrations.AlterField(
            model_name="datagroup",
            name="group_type",
            field=models.ForeignKey(
                default=1,
                help_text="The group type determines which types of data documnets can be uploaded into the data group.",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="dashboard.GroupType",
                verbose_name="group type",
            ),
        ),
        migrations.AlterField(
            model_name="datagroup",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="datagroup",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="datagroupcurationworkflow",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="datagroupcurationworkflow",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="datagroupcurationworkflow",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="datagroupcurationworkflow",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="estimated_records",
            field=models.PositiveIntegerField(
                default=47,
                help_text="Estimated number of documents that the data source will eventually contain.",
                validators=[dashboard.models.data_source.validate_nonzero],
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="documenttype",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="documenttype",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="documenttype",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="documenttype",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="documenttypegrouptypecompatibilty",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="documenttypegrouptypecompatibilty",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="documenttypegrouptypecompatibilty",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="documenttypegrouptypecompatibilty",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dsstoxlookup",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dsstoxlookup",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dsstoxlookup",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dsstoxlookup",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="extractedhabitsandpractices",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="extractedhabitsandpractices",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="extractedhabitsandpractices",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="extractedhabitsandpractices",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="extractedhabitsandpracticesdatatype",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="extractedhabitsandpracticesdatatype",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="extractedhabitsandpracticesdatatype",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="extractedhabitsandpracticesdatatype",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="extractedhabitsandpracticestag",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="extractedhabitsandpracticestag",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="extractedhabitsandpracticestag",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="extractedhabitsandpracticestag",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="extractedhabitsandpracticestagkind",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="extractedhabitsandpracticestagkind",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="extractedhabitsandpracticestagkind",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="extractedhabitsandpracticestagkind",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="extractedhabitsandpracticestopuc",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="extractedhabitsandpracticestopuc",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="extractedhabitsandpracticestopuc",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="extractedhabitsandpracticestopuc",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="extractedhabitsandpracticestotag",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="extractedhabitsandpracticestotag",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="extractedhabitsandpracticestotag",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="extractedhabitsandpracticestotag",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="extractedhpdoc",
            name="extraction_completed",
            field=models.BooleanField(
                default=False,
                help_text="The human health data has been manually extracted.",
            ),
        ),
        migrations.AlterField(
            model_name="extractedlistpresencetag",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="extractedlistpresencetag",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="extractedlistpresencetag",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="extractedlistpresencetag",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="extractedlistpresencetagkind",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="extractedlistpresencetagkind",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="extractedlistpresencetagkind",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="extractedlistpresencetagkind",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="extractedlistpresencetotag",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="extractedlistpresencetotag",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="extractedlistpresencetotag",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="extractedlistpresencetotag",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="extractedtext",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="extractedtext",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="extractedtext",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="extractedtext",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="functionaluse",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="functionaluse",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="functionaluse",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="functionaluse",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="functionalusecategory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="functionalusecategory",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="functionalusecategory",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="functionalusecategory",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="functionalusetorawchem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="functionalusetorawchem",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="functionalusetorawchem",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="functionalusetorawchem",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="grouptype",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="grouptype",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="grouptype",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="grouptype",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="productdocument",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="productdocument",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="productdocument",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="productdocument",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="producttopuc",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="producttopuc",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="producttopuc",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="producttopuc",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="producttopucclassificationmethod",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="producttopucclassificationmethod",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="producttopucclassificationmethod",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="producttopucclassificationmethod",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="producttotag",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="producttotag",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="producttotag",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="producttotag",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="puc",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="puc",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="puc",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="puc",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="puckind",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="puckind",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="puckind",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="puckind",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="puctag",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="puctag",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="puctag",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="puctag",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="puctotag",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="puctotag",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="puctotag",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="puctotag",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="qagroup",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="qagroup",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="qagroup",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="qagroup",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="qanotes",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="qanotes",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="qanotes",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="qanotes",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="rawchem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rawchem",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="rawchem",
            name="provisional",
            field=models.BooleanField(
                default=False,
                help_text="When a RawChem record has a raw_chem_name and raw_cas combination that \n        has already been curated to a certain DSSToxLookup record (and to only one), \n        Factotum will automatically populate the DSSToxLookup foreign key. The provisional \n        field indicates that this assignment was automatically performed without a curator \n        involved.",
            ),
        ),
        migrations.AlterField(
            model_name="rawchem",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rawchem",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="script",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="script",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="script",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="script",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="sourcecategory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sourcecategory",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="sourcecategory",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sourcecategory",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="taxonomy",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="taxonomy",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="taxonomy",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="taxonomy",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="taxonomysource",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="taxonomysource",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="taxonomysource",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="taxonomysource",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="taxonomytopuc",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="taxonomytopuc",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="taxonomytopuc",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="taxonomytopuc",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="unittype",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="unittype",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="unittype",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="unittype",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="weightfractiontype",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Creation timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="weightfractiontype",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the record, inherited from CommonInfo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="weightfractiontype",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Modification timestamp, inherited from CommonInfo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="weightfractiontype",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who modified the record, inherited from CommonInfo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
