# Generated by Django 2.2.20 on 2021-06-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0198_news")]

    operations = [
        migrations.RenameField(
            model_name="extractedhhrec", old_name="media", new_name="medium"
        ),
        migrations.AlterField(
            model_name="extractedhhrec",
            name="num_measure",
            field=models.TextField(
                blank=True, null=True, verbose_name="Numeric Measure"
            ),
        ),
        migrations.AlterField(
            model_name="extractedhhrec",
            name="num_nondetect",
            field=models.TextField(
                blank=True, null=True, verbose_name="Numeric Nondetect"
            ),
        ),
        migrations.AlterField(
            model_name="extractedhhrec",
            name="medium",
            field=models.CharField(blank=True, max_length=30, verbose_name="Medium"),
        ),
    ]
