# Generated by Django 2.2.20 on 2021-07-08 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0199_alter_hhrec_fields")]

    operations = [
        migrations.RunSQL(
            sql="""
            DELETE FROM dashboard_extractedcomposition where rawchem_ptr_id IN (SELECT 
            rawchem_ptr_id
            FROM
            dashboard_extractedlmrec);
            """,
            reverse_sql=migrations.RunSQL.noop,
        )
    ]
