# Generated by Django 2.2.20 on 2021-07-05 12:59

from django.db import migrations, models
import django_db_views.migration_functions
import django_db_views.operations


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0200_extractedlmrec_cleanup")]

    operations = [
        django_db_views.operations.ViewRunPython(
            code=django_db_views.migration_functions.ForwardViewMigration(
                "(SELECT \n            dashboard_extractedlmrec.rawchem_ptr_id as id,\n            dashboard_extractedlmrec.rawchem_ptr_id as rawchem_id,\n            dashboard_extractedlmrec.rawchem_ptr_id,\n            dashboard_extractedlmrec.medium,\n            dashboard_extractedlmrec.num_measure,\n            dashboard_extractedlmrec.harmonized_medium_id\n        FROM\n            dashboard_extractedlmrec\n                INNER JOIN\n            dashboard_rawchem ON (dashboard_extractedlmrec.rawchem_ptr_id = dashboard_rawchem.id)\n        ) \n        UNION \n        (SELECT \n            dashboard_extractedhhrec.rawchem_ptr_id as id,\n            dashboard_extractedhhrec.rawchem_ptr_id as rawchem_id,\n            dashboard_extractedhhrec.rawchem_ptr_id,\n            dashboard_extractedhhrec.medium,\n            dashboard_extractedhhrec.num_measure,\n            NULL AS harmonized_medium_id\n        FROM\n            dashboard_extractedhhrec\n                INNER JOIN\n            dashboard_rawchem ON (dashboard_extractedhhrec.rawchem_ptr_id = dashboard_rawchem.id)\n                INNER JOIN\n            dashboard_dsstoxlookup ON (dashboard_rawchem.dsstox_id = dashboard_dsstoxlookup.id)\n        )",
                "union_lmrec_hhrec",
            ),
            reverse_code=django_db_views.migration_functions.BackwardViewMigration(
                "", "union_lmrec_hhrec"
            ),
            atomic=False,
        ),
        migrations.CreateModel(
            name="UnionExtractedLMHHRec",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medium", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "num_measure",
                    models.TextField(
                        blank=True, null=True, verbose_name="Numeric Measure"
                    ),
                ),
            ],
            options={"db_table": "union_lmrec_hhrec", "managed": False},
        ),
        migrations.AlterField(
            model_name="extractedhhrec",
            name="medium",
            field=models.CharField(blank=True, max_length=30, verbose_name="Medium"),
        ),
    ]
