# Generated by Django 2.2.17 on 2021-07-20 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0202_news_section_upload")]

    operations = [
        migrations.AddField(
            model_name="extractedhhrec",
            name="LOD",
            field=models.FloatField(blank=True, null=True, verbose_name="LOD"),
        ),
        migrations.AddField(
            model_name="extractedhhrec",
            name="LOQ",
            field=models.FloatField(blank=True, null=True, verbose_name="LOQ"),
        ),
        migrations.AddField(
            model_name="extractedhhrec",
            name="detect_freq",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Detection frequency"
            ),
        ),
        migrations.AddField(
            model_name="extractedhhrec",
            name="detect_freq_type",
            field=models.CharField(
                blank=True,
                choices=[("R", "Reported"), ("C", "Computed")],
                max_length=1,
                null=True,
                verbose_name="Detection frequency type",
            ),
        ),
        migrations.AddField(
            model_name="extractedhhrec",
            name="harmonized_medium",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hh_record",
                to="dashboard.HarmonizedMedium",
            ),
        ),
        migrations.AlterField(
            model_name="extractedlmrec",
            name="detect_freq",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Detection frequency"
            ),
        ),
        migrations.AlterField(
            model_name="extractedlmrec",
            name="detect_freq_type",
            field=models.CharField(
                blank=True,
                choices=[("R", "Reported"), ("C", "Computed")],
                max_length=1,
                null=True,
                verbose_name="Detection frequency type",
            ),
        ),
        migrations.AlterField(
            model_name="extractedlmrec",
            name="harmonized_medium",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lm_record",
                to="dashboard.HarmonizedMedium",
            ),
        ),
    ]
