# Generated by Django 2.2.17 on 2021-07-21 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0203_hhe_fields")]

    operations = [
        migrations.RunSQL(
            sql="""
                INSERT INTO dashboard_extractedhpdoc (extractedtext_ptr_id, extraction_completed)
                     SELECT distinct(extracted_text_id), 0
                     FROM dashboard_extractedhabitsandpractices
                     WHERE extracted_text_id not in (select extractedtext_ptr_id from dashboard_extractedhpdoc);
                 """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="extractedhabitsandpractices",
            name="extracted_text",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="practices",
                to="dashboard.ExtractedHPDoc",
            ),
        )
    ]
