# Generated by Django 2.2.20 on 2021-09-03 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0207_statistical_value_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedtext',
            name='cleaning_script',
            field=models.ForeignKey(blank=True, help_text='The script used to clean the data after extraction', limit_choices_to={'script_type': 'DC'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cleaned_documents', to='dashboard.Script'),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE dashboard_extractedtext
                INNER JOIN
                    (SELECT 
                        et.data_document_id AS ddid, MIN(ec.script_id) AS minID
                    FROM
                        dashboard_extractedtext et
                    INNER JOIN dashboard_rawchem rc ON rc.extracted_text_id = et.data_document_id
                    INNER JOIN dashboard_extractedcomposition ec ON ec.rawchem_ptr_id = rc.id
                    WHERE
                        ec.script_id IS NOT NULL
                    GROUP BY et.data_document_id)
                    ec ON ec.ddid = dashboard_extractedtext.data_document_id 
                SET 
                    dashboard_extractedtext.cleaning_script_id = ec.minID
                ;
                 """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
