# Generated by Django 2.2.20 on 2021-09-03 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0209_extractedtext_cleaning_script")]

    operations = [
        migrations.RemoveField(model_name="extractedcomposition", name="script")
    ]
