# Generated by Django 2.2.20 on 2021-09-09 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0211_add_cleaning_qa_fields")]

    operations = [
        migrations.RenameField(
            model_name="qagroup", old_name="extraction_script", new_name="script"
        )
    ]
