# Generated by Django 2.2.20 on 2021-10-01 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0212_rename_qagroup_script_field")]

    operations = [
        migrations.AlterField(
            model_name="extractedtext",
            name="cleaning_qa_checked",
            field=models.BooleanField(
                default=None,
                help_text="The approval status of a cleaned document can be 0 (rejected), 1 (approved) or null (neither approved nor rejected).",
                null=True,
                verbose_name="Cleaning QA status",
            ),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE dashboard_extractedtext
                SET 
                    cleaning_qa_checked = NULL
                ;
                 """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="qagroup",
            name="script",
            field=models.ForeignKey(
                limit_choices_to={"script_type": "EX", "script_type": "DC"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qa_group",
                to="dashboard.Script",
            ),
        ),
    ]
