version: "3.1"

volumes:
  kibanadata:
  kibanaoptdata:


services:
  elasticsearch:
    build: https://github.com/HumanExposure/factotum_elastic.git#${FACTOTUM_ELASTIC_BRANCH:-dev}:elasticsearch
    environment:
      ES_JAVA_OPTS: -Xms${ES_MEMORY_LIMIT:-256m} -Xmx${ES_MEMORY_LIMIT:-256m}
      xpack.graph.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.security.enabled: ${ELASTICSEARCH_SECURITY_ENABLED:-false}
      xpack.security.transport.ssl.enabled: ${ELASTICSEARCH_SECURITY_ENABLED:-false}
      xpack.watcher.enabled: "false"
    ports:
      - ${ELASTICSEARCH_PORT:-9200}:${ELASTICSEARCH_PORT:-9200}

  kibana:
    image: kibana:7.3.1
    restart: unless-stopped
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:${ELASTICSEARCH_PORT:-9200}
      SERVER_PORT: ${KIBANA_PORT:-5601}
      ELASTICSEARCH_USERNAME: "kibana"
      ELASTICSEARCH_PASSWORD: ${KIBANA_PASSWORD:-}
      XPACK_GRAPH_ENABLED: "false"
      XPACK_MONITORING_ENABLED: "false"
      XPACK_REPORTING_ENABLED: "false"
      XPACK_SECURITY_ENABLED: ${ELASTICSEARCH_SECURITY_ENABLED:-"false"}
    ports:
      - ${KIBANA_PORT:-5601}:${KIBANA_PORT:-5601}
    volumes:
      - kibanadata:/usr/share/kibana/data
      - kibanaoptdata:/usr/share/kibana/optimize
    depends_on:
      - elasticsearch

  logstash:
    build: https://github.com/HumanExposure/factotum_elastic.git#${FACTOTUM_ELASTIC_BRANCH:-dev}:logstash
    environment:
      LS_JAVA_OPTS: -Xms${LS_MEMORY_LIMIT:-256m} -Xmx${LS_MEMORY_LIMIT:-256m}
      REINDEX_SCHEDULE: ${REINDEX_SCHEDULE:-*/30 * * * * America/New_York}
      SQL_DATABASE: ${SQL_DATABASE:-factotum}
      SQL_HOST: ${SQL_HOST:-host.docker.internal}
      SQL_PASSWORD: ${SQL_PASSWORD:-}
      SQL_USER: ${SQL_USER:-root}
    ports:
      - ${LOGSTASH_PORT:-5959}:${LOGSTASH_PORT:-5959}/udp

  redis:
    ports:
      - 127.0.0.1:${REDIS_PORT:-6379}:${REDIS_PORT:-6379}
