# Generated by Django 2.2.20 on 2021-12-01 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0214_chem_form_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaSampleSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp, inherited from CommonInfo.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Modification timestamp, inherited from CommonInfo.', null=True)),
                ('source_name', models.CharField(blank=True, help_text='Name of the original data source from where data was extracted and harmonized', max_length=120, verbose_name='Source Name')),
                ('data_type', models.CharField(blank=True, help_text='Whether the original data source was reported as “summary” level data (mean, median, quartile, population, etc.) or “single-sample” level data ', max_length=13, verbose_name='Data Type')),
                ('reported_medium', models.CharField(blank=True, help_text='Reported medium name in the raw data', max_length=200, verbose_name='Reported Medium')),
                ('reported_species', models.CharField(blank=True, help_text='Reported species name in the raw data', max_length=200, verbose_name='Reported Species')),
                ('number_of_observations', models.PositiveIntegerField(default=None, null=True)),
                ('detected_sample_count', models.PositiveIntegerField(default=None, null=True)),
                ('chem_detected_flag', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('UNDETERMINED', 'Undetermined')], help_text='Flag indicating whether a chemical was ever detected in the studied medium', max_length=20, null=True, verbose_name='Chemical Detected')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the record, inherited from CommonInfo.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dsstox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mmdb_summary', to='dashboard.DSSToxLookup', to_field='sid')),
                ('harmonized_medium', models.ForeignKey(blank=True, default=None, help_text='Unique tags used to harmonize across diverse media and species pairs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mmdb_record', to='dashboard.HarmonizedMedium')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who modified the record, inherited from CommonInfo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
